import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { MineState, PlannedBatch, RunLogEntry } from "@/scripts/lib/mine-state";

const PROGRESS_FILE = join(process.cwd(), "scripts", "mine-progress.md");

function fmtUsd(n: number): string {
	return `$${n.toFixed(2)}`;
}

function renderExposure(state: MineState): string {
	const rows: string[] = [
		"| Project | Files | User msgs | Assistant msgs | Turn pairs | After pre-filter |",
		"|---|---:|---:|---:|---:|---:|",
	];
	const totals = { files: 0, userMsgs: 0, assistantMsgs: 0, turnPairs: 0, prefilteredTurns: 0 };
	for (const [project, exp] of Object.entries(state.exposure)) {
		if (!exp) continue;
		rows.push(
			`| ${project} | ${exp.files} | ${exp.userMsgs.toLocaleString()} | ${exp.assistantMsgs.toLocaleString()} | ${exp.turnPairs.toLocaleString()} | ${exp.prefilteredTurns.toLocaleString()} |`,
		);
		totals.files += exp.files;
		totals.userMsgs += exp.userMsgs;
		totals.assistantMsgs += exp.assistantMsgs;
		totals.turnPairs += exp.turnPairs;
		totals.prefilteredTurns += exp.prefilteredTurns;
	}
	rows.push(
		`| **Total** | **${totals.files}** | **${totals.userMsgs.toLocaleString()}** | **${totals.assistantMsgs.toLocaleString()}** | **${totals.turnPairs.toLocaleString()}** | **${totals.prefilteredTurns.toLocaleString()}** |`,
	);
	return rows.join("\n");
}

function renderBatch(b: PlannedBatch): string {
	const cmd = `\`bun run mine --project ${b.project} --batch-size ${b.batchSize} --max-cost-usd ${b.maxCostUsd}\``;
	if (b.status === "pending") {
		return `- [ ] **Batch ${b.id}** — ${cmd} — _not run yet_`;
	}
	const meta = `gated ${b.turnsGated ?? 0}, captured ${b.turnsCaptured ?? 0}, ${fmtUsd(b.usd ?? 0)} on ${b.completedAt?.slice(0, 10) ?? ""}`;
	return `- [x] **Batch ${b.id}** — ${cmd} — ${meta}`;
}

function renderRunLog(log: RunLogEntry[]): string {
	if (log.length === 0) {
		return "_No batches run yet._";
	}
	const rows: string[] = [
		"| # | Date | Project | Turns gated | Turns captured | Tokens in | Tokens out | USD | Cumulative |",
		"|---:|---|---|---:|---:|---:|---:|---:|---:|",
	];
	for (const e of log) {
		rows.push(
			`| ${e.id} | ${e.date.slice(0, 10)} | ${e.project} | ${e.turnsGated} | ${e.turnsCaptured} | ${e.inputTokens.toLocaleString()} | ${e.outputTokens.toLocaleString()} | ${fmtUsd(e.usd)} | ${fmtUsd(e.cumulativeUsd)} |`,
		);
	}
	return rows.join("\n");
}

function renderRemaining(state: MineState): string {
	const pending = state.plannedBatches.filter((b) => b.status === "pending");
	if (pending.length === 0) {
		return "**All planned batches completed.** ✅";
	}
	const totalCaptured = state.runLog.reduce((s, e) => s + e.turnsCaptured, 0);
	const totalGated = state.runLog.reduce((s, e) => s + e.turnsGated, 0);
	return [
		`- **Pending batches:** ${pending.length}`,
		`- **Spent so far:** ${fmtUsd(state.cumulativeUsd)}`,
		`- **Captured so far:** ${totalCaptured} thoughts (across ${totalGated} gated turns)`,
		"",
		"**Next command:**",
		`\`\`\`\nbun run mine --project ${pending[0].project} --batch-size ${pending[0].batchSize} --max-cost-usd ${pending[0].maxCostUsd}\n\`\`\``,
	].join("\n");
}

export function renderProgress(state: MineState): string {
	const measuredAt = state.createdAt.slice(0, 10);
	return `# Echo Mine Progress

_Generated by \`scripts/mine-claude-transcripts.ts\`. Do not hand-edit between runs — the file is regenerated after every batch._

## Total exposure (measured ${measuredAt})

${renderExposure(state)}

## Planned batches

${state.plannedBatches.map(renderBatch).join("\n") || "_(populated after the first dry-run)_"}

## Run log

${renderRunLog(state.runLog)}

## Remaining

${renderRemaining(state)}
`;
}

export function writeProgress(state: MineState): void {
	writeFileSync(PROGRESS_FILE, renderProgress(state), "utf-8");
}

export function progressFilePath(): string {
	return PROGRESS_FILE;
}
